/* eslint-disable */

import { _ } from 'meteor/underscore';

const timezonesList = [{
  name: 'Africa/Abidjan',
}, {
  name: 'Africa/Accra',
}, {
  name: 'Africa/Nairobi',
}, {
  name: 'Africa/Algiers',
}, {
  name: 'Africa/Lagos',
}, {
  name: 'Africa/Bissau',
}, {
  name: 'Africa/Maputo',
}, {
  name: 'Africa/Cairo',
}, {
  name: 'Africa/Casablanca',
}, {
  name: 'Africa/Ceuta',
}, {
  name: 'Africa/El_Aaiun',
}, {
  name: 'Africa/Johannesburg',
}, {
  name: 'Africa/Khartoum',
}, {
  name: 'Africa/Monrovia',
}, {
  name: 'Africa/Ndjamena',
}, {
  name: 'Africa/Tripoli',
}, {
  name: 'Africa/Tunis',
}, {
  name: 'Africa/Windhoek',
}, {
  name: 'America/Adak',
}, {
  name: 'America/Anchorage',
}, {
  name: 'America/Port_of_Spain',
}, {
  name: 'America/Araguaina',
}, {
  name: 'America/Argentina/Buenos_Aires',
}, {
  name: 'America/Argentina/Catamarca',
}, {
  name: 'America/Argentina/Cordoba',
}, {
  name: 'America/Argentina/Jujuy',
}, {
  name: 'America/Argentina/La_Rioja',
}, {
  name: 'America/Argentina/Mendoza',
}, {
  name: 'America/Argentina/Rio_Gallegos',
}, {
  name: 'America/Argentina/Salta',
}, {
  name: 'America/Argentina/San_Juan',
}, {
  name: 'America/Argentina/San_Luis',
}, {
  name: 'America/Argentina/Tucuman',
}, {
  name: 'America/Argentina/Ushuaia',
}, {
  name: 'America/Curacao',
}, {
  name: 'America/Asuncion',
}, {
  name: 'America/Atikokan',
}, {
  name: 'America/Bahia',
}, {
  name: 'America/Bahia_Banderas',
}, {
  name: 'America/Barbados',
}, {
  name: 'America/Belem',
}, {
  name: 'America/Belize',
}, {
  name: 'America/Blanc-Sablon',
}, {
  name: 'America/Boa_Vista',
}, {
  name: 'America/Bogota',
}, {
  name: 'America/Boise',
}, {
  name: 'America/Cambridge_Bay',
}, {
  name: 'America/Campo_Grande',
}, {
  name: 'America/Cancun',
}, {
  name: 'America/Caracas',
}, {
  name: 'America/Cayenne',
}, {
  name: 'America/Panama',
}, {
  name: 'America/Chicago',
}, {
  name: 'America/Chihuahua',
}, {
  name: 'America/Costa_Rica',
}, {
  name: 'America/Creston',
}, {
  name: 'America/Cuiaba',
}, {
  name: 'America/Danmarkshavn',
}, {
  name: 'America/Dawson'
}, {
  name: 'America/Dawson_Creek'
}, {
  name: 'America/Denver'
}, {
  name: 'America/Detroit'
}, {
  name: 'America/Edmonton'
}, {
  name: 'America/Eirunepe'
}, {
  name: 'America/El_Salvador'
}, {
  name: 'America/Tijuana'
}, {
  name: 'America/Fort_Nelson'
}, {
  name: 'America/Fort_Wayne'
}, {
  name: 'America/Fortaleza'
}, {
  name: 'America/Glace_Bay'
}, {
  name: 'America/Godthab'
}, {
  name: 'America/Goose_Bay'
}, {
  name: 'America/Grand_Turk'
}, {
  name: 'America/Guatemala'
}, {
  name: 'America/Guayaquil'
}, {
  name: 'America/Guyana'
}, {
  name: 'America/Halifax'
}, {
  name: 'America/Havana'
}, {
  name: 'America/Hermosillo'
}, {
  name: 'America/Indiana/Knox'
}, {
  name: 'America/Indiana/Marengo'
}, {
  name: 'America/Indiana/Petersburg'
}, {
  name: 'America/Indiana/Tell_City'
}, {
  name: 'America/Indiana/Vevay'
}, {
  name: 'America/Indiana/Vincennes'
}, {
  name: 'America/Indiana/Winamac'
}, {
  name: 'America/Inuvik'
}, {
  name: 'America/Iqaluit'
}, {
  name: 'America/Jamaica'
}, {
  name: 'America/Juneau'
}, {
  name: 'America/Kentucky/Louisville'
}, {
  name: 'America/Kentucky/Monticello'
}, {
  name: 'America/La_Paz'
}, {
  name: 'America/Lima'
}, {
  name: 'America/Los_Angeles'
}, {
  name: 'America/Maceio'
}, {
  name: 'America/Managua'
}, {
  name: 'America/Manaus'
}, {
  name: 'America/Martinique'
}, {
  name: 'America/Matamoros'
}, {
  name: 'America/Mazatlan'
}, {
  name: 'America/Menominee'
}, {
  name: 'America/Merida'
}, {
  name: 'America/Metlakatla'
}, {
  name: 'America/Mexico_City'
}, {
  name: 'America/Miquelon'
}, {
  name: 'America/Moncton'
}, {
  name: 'America/Monterrey'
}, {
  name: 'America/Montevideo'
}, {
  name: 'America/Toronto'
}, {
  name: 'America/Nassau'
}, {
  name: 'America/New_York'
}, {
  name: 'America/Nipigon'
}, {
  name: 'America/Nome'
}, {
  name: 'America/Noronha'
}, {
  name: 'America/North_Dakota/Beulah'
}, {
  name: 'America/North_Dakota/Center'
}, {
  name: 'America/North_Dakota/New_Salem'
}, {
  name: 'America/Ojinaga'
}, {
  name: 'America/Pangnirtung'
}, {
  name: 'America/Paramaribo'
}, {
  name: 'America/Phoenix'
}, {
  name: 'America/Port-au-Prince'
}, {
  name: 'America/Rio_Branco'
}, {
  name: 'America/Porto_Velho'
}, {
  name: 'America/Puerto_Rico'
}, {
  name: 'America/Rainy_River'
}, {
  name: 'America/Rankin_Inlet'
}, {
  name: 'America/Recife'
}, {
  name: 'America/Regina'
}, {
  name: 'America/Resolute'
}, {
  name: 'America/Santarem'
}, {
  name: 'America/Santiago'
}, {
  name: 'America/Santo_Domingo'
}, {
  name: 'America/Sao_Paulo'
}, {
  name: 'America/Scoresbysund'
}, {
  name: 'America/Sitka'
}, {
  name: 'America/St_Johns'
}, {
  name: 'America/Swift_Current'
}, {
  name: 'America/Tegucigalpa'
}, {
  name: 'America/Thule'
}, {
  name: 'America/Thunder_Bay'
}, {
  name: 'America/Vancouver'
}, {
  name: 'America/Whitehorse'
}, {
  name: 'America/Winnipeg'
}, {
  name: 'America/Yakutat'
}, {
  name: 'America/Yellowknife'
}, {
  name: 'Antarctica/Casey'
}, {
  name: 'Antarctica/Davis'
}, {
  name: 'Antarctica/DumontDUrville'
}, {
  name: 'Antarctica/Macquarie'
}, {
  name: 'Antarctica/Mawson'
}, {
  name: 'Pacific/Auckland'
}, {
  name: 'Antarctica/Palmer'
}, {
  name: 'Antarctica/Rothera'
}, {
  name: 'Antarctica/Syowa'
}, {
  name: 'Antarctica/Troll'
}, {
  name: 'Antarctica/Vostok'
}, {
  name: 'Europe/Oslo'
}, {
  name: 'Asia/Riyadh'
}, {
  name: 'Asia/Almaty'
}, {
  name: 'Asia/Amman'
}, {
  name: 'Asia/Anadyr'
}, {
  name: 'Asia/Aqtau'
}, {
  name: 'Asia/Aqtobe'
}, {
  name: 'Asia/Ashgabat'
}, {
  name: 'Asia/Baghdad'
}, {
  name: 'Asia/Qatar'
}, {
  name: 'Asia/Baku'
}, {
  name: 'Asia/Bangkok'
}, {
  name: 'Asia/Barnaul'
}, {
  name: 'Asia/Beirut'
}, {
  name: 'Asia/Bishkek'
}, {
  name: 'Asia/Brunei'
}, {
  name: 'Asia/Kolkata'
}, {
  name: 'Asia/Chita'
}, {
  name: 'Asia/Choibalsan'
}, {
  name: 'Asia/Shanghai'
}, {
  name: 'Asia/Colombo'
}, {
  name: 'Asia/Dhaka'
}, {
  name: 'Asia/Damascus'
}, {
  name: 'Asia/Dili'
}, {
  name: 'Asia/Dubai'
}, {
  name: 'Asia/Dushanbe'
}, {
  name: 'Asia/Gaza'
}, {
  name: 'Asia/Hebron'
}, {
  name: 'Asia/Ho_Chi_Minh'
}, {
  name: 'Asia/Hong_Kong'
}, {
  name: 'Asia/Hovd'
}, {
  name: 'Asia/Irkutsk'
}, {
  name: 'Europe/Istanbul'
}, {
  name: 'Asia/Jakarta'
}, {
  name: 'Asia/Jayapura'
}, {
  name: 'Asia/Jerusalem'
}, {
  name: 'Asia/Kabul'
}, {
  name: 'Asia/Kamchatka'
}, {
  name: 'Asia/Karachi'
}, {
  name: 'Asia/Urumqi'
}, {
  name: 'Asia/Kathmandu'
}, {
  name: 'Asia/Khandyga'
}, {
  name: 'Asia/Krasnoyarsk'
}, {
  name: 'Asia/Kuala_Lumpur'
}, {
  name: 'Asia/Kuching'
}, {
  name: 'Asia/Macau'
}, {
  name: 'Asia/Magadan'
}, {
  name: 'Asia/Makassar'
}, {
  name: 'Asia/Manila'
}, {
  name: 'Asia/Nicosia'
}, {
  name: 'Asia/Novokuznetsk'
}, {
  name: 'Asia/Novosibirsk'
}, {
  name: 'Asia/Omsk'
}, {
  name: 'Asia/Oral'
}, {
  name: 'Asia/Pontianak'
}, {
  name: 'Asia/Pyongyang'
}, {
  name: 'Asia/Qyzylorda'
}, {
  name: 'Asia/Rangoon'
}, {
  name: 'Asia/Sakhalin'
}, {
  name: 'Asia/Samarkand'
}, {
  name: 'Asia/Seoul'
}, {
  name: 'Asia/Singapore'
}, {
  name: 'Asia/Srednekolymsk'
}, {
  name: 'Asia/Taipei'
}, {
  name: 'Asia/Tashkent'
}, {
  name: 'Asia/Tbilisi'
}, {
  name: 'Asia/Tehran'
}, {
  name: 'Asia/Thimphu'
}, {
  name: 'Asia/Tokyo'
}, {
  name: 'Asia/Ulaanbaatar'
}, {
  name: 'Asia/Ust-Nera'
}, {
  name: 'Asia/Vladivostok'
}, {
  name: 'Asia/Yakutsk'
}, {
  name: 'Asia/Yekaterinburg'
}, {
  name: 'Asia/Yerevan'
}, {
  name: 'Atlantic/Azores'
}, {
  name: 'Atlantic/Bermuda'
}, {
  name: 'Atlantic/Canary'
}, {
  name: 'Atlantic/Cape_Verde'
}, {
  name: 'Atlantic/Faroe'
}, {
  name: 'Atlantic/Madeira'
}, {
  name: 'Atlantic/Reykjavik'
}, {
  name: 'Atlantic/South_Georgia'
}, {
  name: 'Atlantic/Stanley'
}, {
  name: 'Australia/Sydney'
}, {
  name: 'Australia/Adelaide'
}, {
  name: 'Australia/Brisbane'
}, {
  name: 'Australia/Broken_Hill'
}, {
  name: 'Australia/Currie'
}, {
  name: 'Australia/Darwin'
}, {
  name: 'Australia/Eucla'
}, {
  name: 'Australia/Hobart'
}, {
  name: 'Australia/Lord_Howe'
}, {
  name: 'Australia/Lindeman'
}, {
  name: 'Australia/Melbourne'
}, {
  name: 'Australia/Perth'
}, {
  name: 'CET'
}, {
  name: 'CST6CDT'
}, {
  name: 'Pacific/Easter'
}, {
  name: 'EET'
}, {
  name: 'EST'
}, {
  name: 'EST5EDT'
}, {
  name: 'Europe/Dublin'
}, {
  name: 'Etc/GMT+0'
}, {
  name: 'Etc/GMT+1'
}, {
  name: 'Etc/GMT+10'
}, {
  name: 'Etc/GMT+11'
}, {
  name: 'Etc/GMT+12'
}, {
  name: 'Etc/GMT+2'
}, {
  name: 'Etc/GMT+3'
}, {
  name: 'Etc/GMT+4'
}, {
  name: 'Etc/GMT+5'
}, {
  name: 'Etc/GMT+6'
}, {
  name: 'Etc/GMT+7'
}, {
  name: 'Etc/GMT+8'
}, {
  name: 'Etc/GMT+9'
}, {
  name: 'Etc/GMT-1'
}, {
  name: 'Etc/GMT-10'
}, {
  name: 'Etc/GMT-11'
}, {
  name: 'Etc/GMT-12'
}, {
  name: 'Etc/GMT-13'
}, {
  name: 'Etc/GMT-14'
}, {
  name: 'Etc/GMT-2'
}, {
  name: 'Etc/GMT-3'
}, {
  name: 'Etc/GMT-4'
}, {
  name: 'Etc/GMT-5'
}, {
  name: 'Etc/GMT-6'
}, {
  name: 'Etc/GMT-7'
}, {
  name: 'Etc/GMT-8'
}, {
  name: 'Etc/GMT-9'
}, {
  name: 'Etc/UCT'
}, {
  name: 'Etc/UTC'
}, {
  name: 'Europe/Amsterdam'
}, {
  name: 'Europe/Andorra'
}, {
  name: 'Europe/Astrakhan'
}, {
  name: 'Europe/Athens'
}, {
  name: 'Europe/London'
}, {
  name: 'Europe/Belgrade'
}, {
  name: 'Europe/Berlin'
}, {
  name: 'Europe/Prague'
}, {
  name: 'Europe/Brussels'
}, {
  name: 'Europe/Bucharest'
}, {
  name: 'Europe/Budapest'
}, {
  name: 'Europe/Zurich'
}, {
  name: 'Europe/Chisinau'
}, {
  name: 'Europe/Copenhagen'
}, {
  name: 'Europe/Gibraltar'
}, {
  name: 'Europe/Helsinki'
}, {
  name: 'Europe/Kaliningrad'
}, {
  name: 'Europe/Kiev'
}, {
  name: 'Europe/Lisbon'
}, {
  name: 'Europe/Luxembourg'
}, {
  name: 'Europe/Madrid'
}, {
  name: 'Europe/Malta'
}, {
  name: 'Europe/Minsk'
}, {
  name: 'Europe/Monaco'
}, {
  name: 'Europe/Moscow'
}, {
  name: 'Europe/Paris'
}, {
  name: 'Europe/Riga'
}, {
  name: 'Europe/Rome'
}, {
  name: 'Europe/Samara'
}, {
  name: 'Europe/Simferopol'
}, {
  name: 'Europe/Sofia'
}, {
  name: 'Europe/Stockholm'
}, {
  name: 'Europe/Tallinn'
}, {
  name: 'Europe/Tirane'
}, {
  name: 'Europe/Ulyanovsk'
}, {
  name: 'Europe/Uzhgorod'
}, {
  name: 'Europe/Vienna'
}, {
  name: 'Europe/Vilnius'
}, {
  name: 'Europe/Volgograd'
}, {
  name: 'Europe/Warsaw'
}, {
  name: 'Europe/Zaporozhye'
}, {
  name: 'HST'
}, {
  name: 'Indian/Chagos'
}, {
  name: 'Indian/Christmas'
}, {
  name: 'Indian/Cocos'
}, {
  name: 'Indian/Kerguelen'
}, {
  name: 'Indian/Mahe'
}, {
  name: 'Indian/Maldives'
}, {
  name: 'Indian/Mauritius'
}, {
  name: 'Indian/Reunion'
}, {
  name: 'Pacific/Kwajalein'
}, {
  name: 'MET'
}, {
  name: 'MST'
}, {
  name: 'MST7MDT'
}, {
  name: 'Pacific/Chatham'
}, {
  name: 'PST8PDT'
}, {
  name: 'Pacific/Apia'
}, {
  name: 'Pacific/Bougainville'
}, {
  name: 'Pacific/Chuuk'
}, {
  name: 'Pacific/Efate'
}, {
  name: 'Pacific/Enderbury'
}, {
  name: 'Pacific/Fakaofo'
}, {
  name: 'Pacific/Fiji'
}, {
  name: 'Pacific/Funafuti'
}, {
  name: 'Pacific/Galapagos'
}, {
  name: 'Pacific/Gambier'
}, {
  name: 'Pacific/Guadalcanal'
}, {
  name: 'Pacific/Guam'
}, {
  name: 'Pacific/Honolulu'
}, {
  name: 'Pacific/Kiritimati'
}, {
  name: 'Pacific/Kosrae'
}, {
  name: 'Pacific/Majuro'
}, {
  name: 'Pacific/Marquesas'
}, {
  name: 'Pacific/Pago_Pago'
}, {
  name: 'Pacific/Nauru'
}, {
  name: 'Pacific/Niue'
}, {
  name: 'Pacific/Norfolk'
}, {
  name: 'Pacific/Noumea'
}, {
  name: 'Pacific/Palau'
}, {
  name: 'Pacific/Pitcairn'
}, {
  name: 'Pacific/Pohnpei'
}, {
  name: 'Pacific/Port_Moresby'
}, {
  name: 'Pacific/Rarotonga'
}, {
  name: 'Pacific/Tahiti'
}, {
  name: 'Pacific/Tarawa'
}, {
  name: 'Pacific/Tongatapu'
}, {
  name: 'Pacific/Wake'
}, {
  name: 'Pacific/Wallis'
}, {
  name: 'WET'
}];

export default _.sortBy(timezonesList, 'name');
